---
# Install WP CLI, test install with wp --info
- name: Download wp-cli.phar and set it up as wp for all users
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0775'
# Change php-fpm config
# /etc/php/8.0/fpm/php.ini update upload_max_filesize = 50M and post_max_size = 64M
- name: Change php-fpm config for upload_max_filesize
  replace:
    path: /etc/php/{{php.version}}/fpm/php.ini
    regexp: "upload_max_filesize.*\n"
    replace: "upload_max_filesize = 50M\n"
  notify:
    - reload php-fpm
- name: Change php-fpm config for post_max_size
  replace:
    path: /etc/php/{{php.version}}/fpm/php.ini
    regexp: "post_max_size.*\n"
    replace: "post_max_size = 64M\n"
  notify:
    - reload php-fpm
- name: Change php-fpm config for memory_limit
  replace:
    path: /etc/php/{{php.version}}/fpm/php.ini
    regexp: "memory_limit.*\n"
    replace: "memory_limit = 512M\n"
  notify:
    - reload php-fpm

- name: Restart and enable PHP-FPM service
  service: 
    name: "{{item}}"
    state: restarted 
    enabled: yes
  loop: 
    - "php{{php.version}}-fpm"